on:
  push:
    branches:
      - main
    # Filter events based on the commit message
    paths-ignore:
      - 'none'
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Check if the commit message contains the specified string
      - name: Check Commit Message
        if: contains(github.event.head_commit.message, 'Docker Image CI for GHCR')
        run: exit 0  # Exit successfully to skip the rest of the steps

      - name: Build the package
        run: mvn --batch-mode -DskipTests package

      - name: Run the unit tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Build and push the image
        run: |
          docker login --username bolabanj --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/bolabanj/guitar-inventory-management:latest --file Dockerfile .  
          docker push ghcr.io/bolabanj/guitar-inventory-management:latest 
